# Generated by Django 6.0.6 on 2026-06-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50)),
                ('customer_name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('delivery_date', models.DateField()),
            ],
        ),
    ]
