# Generated by Django 6.0.6 on 2026-07-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_created_at_ticket_ticket_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
